### ISSUE TITLE
Fix rule SS6606: Properly check if replacement of `||` by `??` is actually safe

### ISSUE THREAD

**Issue by victor-diez-sonarsource** [SonarSource/SonarJS#3986] opened 2023-06-23 10:16 UTC
Reported in community: https://community.sonarsource.com/t/js-ts-rule-s6606-suggestion-to-replace-with-is-ambiguous/94498

**Comment by vdiez** [comment] 2023-11-02 12:24
Close as duplicate of #3936

**Closed** 2023-11-02 12:27 UTC
