### ISSUE TITLE
Upgrade typescript-eslint to v6.4

### ISSUE THREAD

**Issue by alexander-kamushkin-sonarsource** [SonarSource/SonarJS#4062] opened 2023-08-16 12:00 UTC
https://typescript-eslint.io/blog/announcing-typescript-eslint-v6/
https://github.com/SonarSource/SonarJS/issues/4005

**Comment by yassin-kammoun-sonarsource** [comment] 2023-08-31 13:02
Duplicate of #4005

**Closed by yassin-kammoun-sonarsource** 2023-08-31 13:02 UTC
Labels: hardening
