### ISSUE TITLE
Fix FP S2699 (`assertions-in-tests`): Detect `expect` provided by the test callback on concurrent tests

### ISSUE THREAD

**Issue by yassin-kammoun-sonarsource** [SonarSource/SonarJS#4507] opened 2024-01-17 15:06 UTC
https://community.sonarsource.com/t/vitest-and-describe-concurrent-tests-should-include-assertions/107121

**Comment by ericmorand-sonarsource** [comment] 2024-03-26 15:56
This issue is a duplicate of #4459. Please refer to the added test `vitest concurrent test cases` for confirmation.

**Closed** 2024-03-27 09:30 UTC
Labels: type: false positive, must-have
