### ISSUE TITLE
Update to 4.2.1.6529 breaks SonarQube

### ISSUE THREAD

**Issue by larsauswsw** [SonarSource/SonarJS#1075] opened 2018-09-28 12:53 UTC
**I want to report a bug.**

**SonarJS version:** 4.2.1.6529<br>
**SonarQube version:** 6.7.3 (build 38370) <br>

**Reproducer** 
I updated the plugin version from 4,.1.0.6085 to 4.2.1.6529 over the marketplace. After the update my SonarQube instance won't start with the following Exception:

**Logs**
2018.09.28 14:42:04 INFO  web[][o.s.s.q.RegisterQualityProfiles] Update profile jsp/FindBugs Security JSP
2018.09.28 14:42:04 INFO  web[][o.s.s.q.RegisterQualityProfiles] Update profile js/Sonar way Recommended
2018.09.28 14:42:04 ERROR web[][o.s.s.p.Platform] Background initialization failed. Stopping SonarQube
org.sonar.server.exceptions.BadRequestException: **Rule not found: javascript:LineLength**
	at org.sonar.server.exceptions.BadRequestException.create(BadRequestException.java:44)
	at org.sonar.server.exceptions.BadRequestException.create(BadRequestException.java:48)
	at org.sonar.server.ws.WsUtils.checkRequest(WsUtils.java:71)
	at org.sonar.server.qualityprofile.RuleActivatorContextFactory.initRule(RuleActivatorContextFactory.java:74)
	at org.sonar.server.qualityprofile.RuleActivatorContextFactory.init(RuleActivatorContextFactory.java:59)
	at org.sonar.server.qualityprofile.RuleActivatorContextFactory.createForBuiltIn(RuleActivatorContextFactory.java:50)
	at org.sonar.server.qualityprofile.RuleActivator.activateOnBuiltInRulesProfile(RuleActivator.java:82)
	at org.sonar.server.qualityprofile.BuiltInQProfileUpdateImpl.lambda$update$0(BuiltInQProfileUpdateImpl.java:59)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at org.sonar.server.qualityprofile.BuiltInQProfileUpdateImpl.update(BuiltInQProfileUpdateImpl.java:56)
	at org.sonar.server.qualityprofile.RegisterQualityProfiles.update(RegisterQualityProfiles.java:118)
	at org.sonar.server.qualityprofile.RegisterQualityProfiles.lambda$start$1(RegisterQualityProfiles.java:85)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at org.sonar.server.qualityprofile.RegisterQualityProfiles.start(RegisterQualityProfiles.java:80)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.picocontainer.lifecycle.ReflectionLifecycleStrategy.invokeMethod(ReflectionLifecycleStrategy.java:110)
	at org.picocontainer.lifecycle.ReflectionLifecycleStrategy.start(ReflectionLifecycleStrategy.java:89)
	at org.picocontainer.injectors.AbstractInjectionFactory$LifecycleAdapter.start(AbstractInjectionFactory.java:84)
	at org.picocontainer.behaviors.AbstractBehavior.start(AbstractBehavior.java:169)
	at org.picocontainer.behaviors.Stored$RealComponentLifecycle.start(Stored.java:132)
	at org.picocontainer.behaviors.Stored.start(Stored.java:110)
	at org.picocontainer.DefaultPicoContainer.potentiallyStartAdapter(DefaultPicoContainer.java:1016)
	at org.picocontainer.DefaultPicoContainer.startAdapters(DefaultPicoContainer.java:1009)
	at org.picocontainer.DefaultPicoContainer.start(DefaultPicoContainer.java:767)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:134)
	at org.sonar.server.platform.platformlevel.PlatformLevel.start(PlatformLevel.java:90)
	at org.sonar.server.platform.platformlevel.PlatformLevelStartup.access$001(PlatformLevelStartup.java:45)
	at org.sonar.server.platform.platformlevel.PlatformLevelStartup$1.doPrivileged(PlatformLevelStartup.java:83)
	at org.sonar.server.user.DoPrivileged.execute(DoPrivileged.java:45)
	at org.sonar.server.platform.platformlevel.PlatformLevelStartup.start(PlatformLevelStartup.java:80)
	at org.sonar.server.platform.Platform.executeStartupTasks(Platform.java:196)
	at org.sonar.server.platform.Platform.access$400(Platform.java:46)
	at org.sonar.server.platform.Platform$1.lambda$doRun$1(Platform.java:121)
	at org.sonar.server.platform.Platform$AutoStarterRunnable.runIfNotAborted(Platform.java:371)
	at org.sonar.server.platform.Platform$1.doRun(Platform.java:121)
	at org.sonar.server.platform.Platform$AutoStarterRunnable.run(Platform.java:355)
	at java.lang.Thread.run(Thread.java:748)
2018.09.28 14:42:04 INFO  web[][o.s.p.StopWatcher] Stopping process

**Expected behavior**

Update with no problem.

**Comment by ehartmann** [comment] 2018-10-03 14:49
Hi @larsauswsw ,

I'm not able to reproduce your issue. According to the log, there is a missing database record in your database at the launch of SonarQube.
This should not happen, I have two hypothesis :

1. something is corrupted in your database (you can confirm that by executing  ```SELECT * FROM rules WHERE plugin_key='javascript' AND plugin_rule_key='LineLength';``` on your database).
2. you launched multiple SonarQube instance on the same database.

Cheers,

**Comment by larsauswsw** [comment] 2018-10-05 12:17
I can reproduce it. 
- SonarQube 6.7.3 without javascript plugin
- install plugin over marketplace
- restart
- error while start

The strange thing: after installation I did the SQL Query.

`SELECT * FROM rules WHERE plugin_key='javascript' AND plugin_rule_key='LineLength';` -> 0 results
`SELECT * FROM rules WHERE plugin_key='javascript' AND plugin_rule_key like 'LineLength';` -> 0 results

`SELECT * FROM rules WHERE plugin_key='javascript' AND plugin_rule_key like '%LineLength';` -> 1 result

**Result:**
678;"Lines should not be too long";"LineLength";"";"javascript";"Having to scroll horizontally makes it harder to get a quick overview and understanding of any piece of code";2;;"READY";"js";"CONSTANT_ISSUE";"";"1min";"";"convention";f;"HTML";1465807855117;1538741232599;1;"javascript"

Maybe some whitespaces?

**Comment by ehartmann** [comment] 2018-10-05 12:19
Pretty strange, which database are you using ?

**Comment by larsauswsw** [comment] 2018-10-05 12:36
"PostgreSQL 9.4.18 on x86_64-unknown-linux-gnu (Debian 9.4.18-2.pgdg70+1), compiled by gcc (Debian 4.7.2-5) 4.7.2, 64-bit"

**Comment by larsauswsw** [comment] 2018-10-05 12:43
In SonarQube 6.7.5 even version 4.1.0 is not usable with the same error.

**Comment by larsauswsw** [comment] 2018-10-05 12:45
I deleted all javascript rules with `Delete FROM rules WHERE plugin_key='javascript';` and installed the plugin in version 4.2.1.

Now it works fine.

**Comment by ehartmann** [comment] 2018-10-05 13:19
It looks like the database was corrupted at some point or maybe the indices were not up to date.
As it works now, I'm closing this issue.

**Closed by ehartmann** 2018-10-05 13:19 UTC
